apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
spec:
  selector:
    matchLabels:
      app: myimage
  replicas: 4
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage
        image: myimage:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
